version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "first"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-n5234blcgu98"
s3_prefix = "first"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
