AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Globals:
  Function:
    Timeout: 3
    CodeUri: hello_world/
    Runtime: python3.9
    Architectures:
      - x86_64
    Environment:
      Variables:
        USER_ENV: !Ref User

Parameters:
  User:
    Type: String
    Default: dev

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${User}-GreetPost"
      Handler: app.lambda_handler
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Events:
        greet:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: post

  GreetListFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${User}-GreetGet"
      Handler: get_greets.lambda_handler
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: get


  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "${User}-UserData"

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/hello"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
